hash-format = "sha256"

[[files]]
file = "README.md"
hash = "f0b7af943b908e41876ad17a73d31718dfd02404873161e17126ba35129440c7"

[[files]]
file = "mods/balm.pw.toml"
hash = "0fb3ed7eaa615380d4d7844f0225f4ec4a6509cdfe01920387ed7b2bd923e4d7"
metafile = true

[[files]]
file = "mods/cameraoverhaul.pw.toml"
hash = "0a9898846a8d2e683f378a033da718c1ddc19eaaf422604d77f6de76d36a489d"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "974049895ae886659595771f83bd5a03da5b969b402a029694a2978d1ffd7aa0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a216e613b5ada8a83972394c8b52331388f6d3e41187a04c3bced3f1752bea70"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "716b671d0b15ea17c788c571620eac83207bb2b6e8dbe0d33319838478f21efc"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "937acae581d8c4340d141446a7adb5b3b1915130fd483bee067d45aade834a8a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7ade9694388d80def1aba6b3653a1a0ea8a68eb14a42e2bffd076fd1335a5ce8"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "dff937930734d00e3cd2c644d20d5015df3ad53cc9d23fae2704326774cadbad"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "e4104c5878b48368908e67cd0710c119b94652365c4e568e4e2ec0734a06e9dd"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "d246630b697cddeda5d6a3215b078f49d663c079b71acdbbdd1c50eb83505ca9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "17d4083ec0d10cc2f5ca3a750b864dff5def75aa6c71f434ab701e2123e1b02c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "1e4e37a781f247c943ccfd23d3a6cdf317297a4ef43743fe5141d1f16e81876b"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "ce1a109ba7d2637596ab6b7c001716437e1bef89f337dc3fb31ca950a46e79c3"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "f4360b358a2607a715e0a361872b4d08c85e872f2f86c6ddf4c531fa6ff7cd25"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e10c94949bb58b8cfa9993a9f60c9283d5858d4d55fc450dbff2953644f45047"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6eea5e1db3dbca126b82f211bf0d2fcf2cf13097023fdef3dd668e48581a73d0"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "bf387fb939f9a4a7f0dbd45542c9681244785f8f0daf83eb3b7d3a9a33709ec6"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "0993352e081593fca386a8a4e6473ece541a27e018c8384239f27f79d73133a0"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "b5bd65035ac700f23a707d136e0150bfe950faa722edb384d6507ddb7f674f1c"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "5dff8bca658ae787c75fd2a37a40c8512a5fbc8a2421d106f94e08c8640b9075"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "e3eabb9d68f1b7bfc48bdd7846d0b743f3b5fbeaeebf63fecf1ced3d79acdc7e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1745f4ec1732e16be5f2c88780a66ca2a94c76c06c5e862db0b2c6cf63b16a47"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "a6948eb25808d55a8dc3b9a64999181ebae738c3679ced2981c7c1ec34b9b0b6"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "a21afaf5777783244b77cd9b4333759bfa94ddd3ddc359f1a00355100430f177"
metafile = true

[[files]]
file = "mods/tough-as-nails.pw.toml"
hash = "b9cfed15096f58b5aa41aefebbd14136712e36c8a40eff415025e93c2bbbcac9"
metafile = true

[[files]]
file = "mods/trash-cans.pw.toml"
hash = "9239555187f50289032bcaa6285bd8766ea465dc8e0f9015a22314ed8078cae5"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "dacdbbcdf09323f1ce3646dcddb4c10d791b0306aa0cedf3c4c97d9f5136d06e"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "3a3eac5ffe0a6299390ee43c0dcefacf1884164949ccbf32d9e862e4de4beecb"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "07b6eae147b1e041132420c4731e6e6449b99ec8fcf6251b5ce5ce08638fa322"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "9634d746c3589372f1b0d38556f340564b3e65393ae2457d6e4fb15f6e261cd9"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "ae2321b4aaafeeefd83d37b0268a18b02f7efd6b6a40b5873432d8f4ff3bf95b"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "8aac4bde39fa5392fddd8e26c7254f975e6982c9791d2ec70ad9e6ca93f69f60"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ea0eb6ab539b43926503901694913866aa81a9a644cd3469080214a7ca785db2"
metafile = true
