name = "Fabric of Joy"
author = "Keksiu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9793d6c5ecaa5f1fff35fd9b80b092cdd5c8abc0732ca97dcf414386d36925b1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
