name = "Fabric of Joy"
author = "Keksiu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01b4a2a98c3d845d40bd2fb1554a0798430bfc0f190ffb2453530d43add1aedd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
